Repository BepInEx/Il2CppInterop, pull requests merged in 2024-09, with the labels that each got.

#134 Fix class injector abstract method handling
  Il2CppInterop.Runtime/Injection/ClassInjector.cs
Labels: injection

#160 Special-case System.Enum as a generic constraint
  Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
  Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
  Il2CppInterop.Generator/Passes/Pass13FillGenericConstraints.cs
  Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs
Labels: bug, generation

#161 Add debugger display attributes to the generator context types
  Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs
  Il2CppInterop.Generator/Contexts/FieldRewriteContext.cs
  Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
  Il2CppInterop.Generator/Contexts/TypeRewriteContext.cs
Labels: generation

#159 Treat pointers as value types
  Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
  Il2CppInterop.Generator/Extensions/ILGeneratorEx.cs
  Il2CppInterop.Generator/Utils/FieldAccessorGenerator.cs
  Il2CppInterop.Generator/Utils/UnstripGenerator.cs
Labels: bug, generation

#162 Unstrip fields for constants and new structs
  Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
  Il2CppInterop.Generator/Passes/Pass80UnstripFields.cs
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: enhancement, generation

#158 Improve type resolution for unstripping
  Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs
Labels: enhancement, generation

#168 Expand Macros Before Unstripping
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: generation

#154 Fix Invalid Generic Parameter Names
  Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
  Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
  Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs
Labels: generation

#169 Improve property resolution during unstripping
  Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: generation

#157 Unstrip Exception Handlers
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: generation

#170 Improve Generics Unstripping
  Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: generation

#179 Prevent null strings in OriginalName
  Il2CppInterop.Generator/Passes/Pass22GenerateEnums.cs
Labels: bug, generation

#181 Fix null ParameterDefinition when copying
  Il2CppInterop.Generator/Passes/Pass19CopyMethodParameters.cs
Labels: bug, generation

#180 Assign method metadata tokens before writing
  Il2CppInterop.Generator/Passes/Pass90WriteToDisk.cs
Labels: bug, generation

#171 Improve corlib type resolution during unstripping
  Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
  Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
  Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs
  Il2CppInterop.Generator/Utils/UnstripTranslator.cs
Labels: generation
